# Generated by Django 4.0.3 on 2022-04-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
