# Generated by Django 4.0.3 on 2022-04-08 20:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_remove_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photos'),
        ),
    ]
