# Generated by Django 4.0.3 on 2022-04-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
